feat: add log decoder helper and import web3 [serverless]
fleekxyz/non-fungible-apps pull request #219
Opened 2023-04-12 10:07 UTC by EmperorOrokuSaki

2023-04-12 16:13 UTC, zoruka commented on serverless/src/libs/log-decoder.ts
> +var web3 = new Web3(Web3.givenProvider || "ws://localhost:17895");
```suggestion
const web3 = new Web3(Web3.givenProvider || "ws://localhost:17895");
```

2023-04-12 16:14 UTC, zoruka commented on serverless/src/libs/log-decoder.ts
> +};
```suggestion
export const logDecoder = web3.eth.abi.decodeLog;
```

2023-04-24 15:37 UTC, jsonsivar requested changes
As discussed in scrum, let's close this and add web3 export to our solidity helper and we can use the web3 decoder function directly from that exported web3 instance.

2023-04-24 15:52 UTC, EmperorOrokuSaki commented
will be covered in #232

2023-04-24 15:52 UTC, closed without merging