Release v0.0.6 to main
fleekxyz/non-fungible-apps pull request #226
Opened 2023-04-14 18:40 UTC by jsonsivar

### Features
* Ethereum support (Goerli)
* contracts: ens integration
* contracts: verifier field and modifier
* contacts: prevent direct calls to implementation contract
* ui: simple create AP flow
* ui: navbar
* ui: form validations
* ui: explore view skeleton
* ui: explore view pagination
* ui: card list component
* ui: search on list
* ui: sort on list

### Fixes
* ui: color picker style
* ui: broken create ap button
* ui: graphql query (overlapping field)
* ui: colors not showing on firefox
* ui: alchemy keys missing

### Chores
* aws (serverless) project setup
* eslint cleanups
* contracts: change _billing to private
* ui: XYZ deployment
* ui: remove storybook
* ui: remove ens storage
* ui: remove unused refs
* ui: add base theme color black
* ui: drip stitches export
* ui: refactor style combobox
* ui: change mint forms fields order

2023-04-17 15:35 UTC, EmperorOrokuSaki requested changes
The subgraph tests are failing as expected. I suggest we remove all of them.
See #168

2023-04-17 16:53 UTC, csosamorales approved these changes
Left some comments for the next release

2023-04-17 16:53 UTC, csosamorales commented on ui/src/components/core/color-picker/color-picker.tsx
> +          {/* TODO crate color picker component */}
I'm gonna remove this comment for the next release

2023-04-17 16:53 UTC, csosamorales commented on ui/src/components/core/input/input-file.styles.ts
> +    //TODO add error state
will remove this also

2023-04-19 16:23 UTC, EmperorOrokuSaki approved these changes

2023-04-20 13:26 UTC, zoruka approved these changes

2023-04-20 15:23 UTC, merged