Update CONTRIBUTING.md
fleekxyz/non-fungible-apps pull request #64
Opened 2022-12-22 17:49 UTC by EmperorOrokuSaki

2022-12-30 17:50 UTC, jsonsivar requested changes

2022-12-30 17:50 UTC, jsonsivar commented on CONTRIBUTING.md
> +If you want to help us improve the project you can always start a conversation through the [issues page](https://github.com/fleekxyz/non-fungible-apps/issues). Please, make sure you are respectful to
I would say start a conversation through the discussions section or if you spot an issue then create an issue.

2022-12-30 17:50 UTC, jsonsivar commented on CONTRIBUTING.md
> +1. Search for existing related Issues and PRs before creating your own.
Did we mean to remove the top section? I see the same 1-3 above

2022-12-30 17:50 UTC, jsonsivar commented on CONTRIBUTING.md
> +You can create branches from the `main` branch and name them in accordance with **conventional
What about using `develop` first?

2023-01-10 18:38 UTC, zoruka approved these changes

2023-01-19 17:32 UTC, jsonsivar approved these changes

2023-01-19 17:35 UTC, merged