feat: UI improvements
fleekxyz/non-fungible-apps pull request #67
Opened 2022-12-30 17:08 UTC by csosamorales

Related tasks:
- add paste button on Owner Address field (UI12)
- add Site Card pointer onHover (UI13)
- add tooltip on attributes card (UI14)
- add icons on wallet button

2022-12-30 17:23 UTC, csosamorales commented
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/52458215/210096565-7fcb8147-205f-4f6d-9b0c-889b2949a586.png">

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/52458215/210096623-5c886ec3-746d-4eb8-9036-d43624ec2af4.png">

![feat_ UI improvements by csosamorales · Pull Request  67 · fleekxyz_non-fungible-apps](https://user-images.githubusercontent.com/52458215/210096758-6547e3b3-7528-4bc8-a715-d6fc63872a06.gif)

2023-01-09 18:00 UTC, zoruka requested changes
Left some comments of possible improvements. For a latter instance I think we should at all avoid using `px` units to defining sizes all of them should be replaced for `rem` as it makes really easier to improve the application responsiviness. Also is important to notice that all the hardcoded colors should be switched to a theming file following the UI framework suitability like here https://chakra-ui.com/docs/styled-system/customize-theme. These changes are the point to make our app more maintainable as the project grows, almost every time that some kind of information is repeated seems like it should be abstracted away so changes can be done easily with a single source of truth.

2023-01-09 18:02 UTC, zoruka commented
Another comment, just to keep patterns I think this PR should be called `refactor: ...` as it is not adding new features but improving the current ones.

2023-01-09 20:00 UTC, csosamorales commented on ui/src/components/wallet-button/wallet-icons.tsx
> +  return <Icon as={FaWallet} />;
cool thanks! I had something similar on mind and that example helps me a lot 🙏🏼

2023-01-09 20:08 UTC, csosamorales commented on ui/src/components/wallet-button/wallet-icons.tsx
> +import Metamask from 'assets/MetaMask.png';
I agree about the SVG, but didn't find any metamask SVG file 😞

2023-01-10 21:55 UTC, zoruka requested changes
Overall the implementations looks good to me. Just a small change request.

2023-01-10 21:55 UTC, zoruka commented on ui/src/views/mint-site/mint-site.tsx
> +          }}
Let's avoid adding functions in the middle of the component render to improve readability.

2023-01-11 21:13 UTC, zoruka approved these changes

2023-01-11 21:34 UTC, merged